--
-- PostgreSQL Sequences
-- Definição de todas as sequências (IDENTITY e AUTO INCREMENT)
--

-- Função para adicionar identidade apenas se não existir
DO $$
BEGIN
    -- customer_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'customer'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.customer_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- customer_order_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'customer_order'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.customer_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.customer_order_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- customer_order_food_item_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'customer_order_food_item'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.customer_order_food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.customer_order_food_item_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- food_item_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'food_item'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.food_item_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- food_item_image_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'food_item_image'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.food_item_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.food_item_image_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- kitchen_order_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'kitchen_order'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.kitchen_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.kitchen_order_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- kitchen_order_food_item_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'kitchen_order_food_item'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.kitchen_order_food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.kitchen_order_food_item_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- notifications_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'notifications'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.notifications_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

    -- payment_id_seq
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'payment'
        AND column_name = 'id'
        AND column_default LIKE 'nextval%'
    ) THEN
        ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
            SEQUENCE NAME public.payment_id_seq
            START WITH 1
            INCREMENT BY 1
            NO MINVALUE
            NO MAXVALUE
            CACHE 1
        );
    END IF;

END $$;
