--
-- PostgreSQL Sequences
-- Definição de todas as sequências (IDENTITY e AUTO INCREMENT)
--

--
-- Name: customer_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.customer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: customer_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.customer_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: customer_order_food_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.customer_order_food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customer_order_food_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: food_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.food_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: kitchen_order_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.kitchen_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kitchen_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: kitchen_order_food_item_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.kitchen_order_food_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kitchen_order_food_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--
ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
